### ISSUE TITLE
Fix the image in the Readme.md to better suit dark and light mode users.

### ISSUE THREAD

**Issue by captraj** [Aisuko/notebooks#8]
The image in the readme of the project file that is : images/The Field of AI in Layers.svg has a transparent background which needs to be changed to a white background in this case, as the labels are black in color and do not change when the user in github is using dark mode, which most use. This problem can be solved by changing the image's backgroud to white that would provide enough contrast to readers.
![image](https://github.com/Aisuko/notebooks/assets/76588598/440b8537-f280-4e63-af07-05f8664871b8)

**Comment by Aisuko** [comment]
Thanks

**Comment by captraj** [comment]
You're welcome.
